version: v3.1-refine-1
weights:
  mROI: 0.4
  uplift: 0.3
  delta_mape: 0.2   # Formel nutzt (1 - delta_mape)
  freshness: 0.1
validation:
  review_window_days: 14
  min_avg_health_soft: 0.50
  min_avg_health_hard: 0.55
  tolerance: 0.0001
  strict_window_threshold: 0.2   # >20% veraltet => ERROR bei --strict-window
aggregation:
  weighted: false
  weight_field: "weight"
logging:
  json_lines: true
