name: Health Telemetry Validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: "Install deps"
        run: |
          python -m pip install -r requirements.txt

      - name: "Run validation (PR: soft gate)"
        run: |
          python artefacts/screening_runner.py --gate soft --now "${{ github.event.pull_request.updated_at }}"

  validate-main:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: "Install deps"
        run: |
          python -m pip install -r requirements.txt

      - name: "Run validation (main: hard gate, strict window)"
        run: |
          python artefacts/screening_runner.py --strict-window --gate hard --now "${{ github.event.head_commit.timestamp }}"
