name: Health Telemetry Validation
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Run validation (PR: soft gate)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          python artefacts/screening_runner.py --now "${{ github.event.pull_request.updated_at }}"

      - name: Run validation (main: hard gate, strict window)
        if: ${{ github.event_name == 'push' }}
        run: |
          python artefacts/screening_runner.py --strict-window --now "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
