name: Task Index Check

permissions:
  contents: read

concurrency:
  group: tasks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "11 6 * * *" # täglich 06:11 UTC

jobs:
  validate-tasks-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install jsonschema
      - name: Run tasks monitor (PR)
        id: monitor
        run: |
          python artefacts/tasks_monitor.py | tee tasks.jsonl
      - name: Summary (PR)
        run: |
          {
            echo "## Human-in-the-Loop Task Check (PR)"
            echo "- Blocking open: $(grep -c 'open_or_overdue_blocking' tasks.jsonl || true)"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Upload task log
        uses: actions/upload-artifact@v4
        with:
          name: tasks-log-pr
          path: tasks.jsonl
          retention-days: 7

  validate-tasks-main:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install jsonschema
      - name: Run tasks monitor (main, blocking)
        id: monitor
        run: |
          python artefacts/tasks_monitor.py | tee tasks.jsonl
      - name: Summary (main)
        run: |
          {
            echo "## Human-in-the-Loop Task Check (main)"
            echo "- Blocking open: $(grep -c 'open_or_overdue_blocking' tasks.jsonl || true)"
            echo ""
            echo "_Hinweis: Pipeline FAILt, solange blockierende Tasks offen/überfällig sind._"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Upload task log
        uses: actions/upload-artifact@v4
        with:
          name: tasks-log-main
          path: tasks.jsonl
          retention-days: 7
